[2023-06-08T19:21:45.670+0000] {processor.py:153} INFO - Started process (PID=19292) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:21:45.671+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:21:45.672+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:21:45.672+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:21:45.690+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:21:45.687+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:21:45.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:21:45.709+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.041 seconds
[2023-06-08T19:22:16.221+0000] {processor.py:153} INFO - Started process (PID=19346) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:16.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:22:16.222+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:22:16.222+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:16.233+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:22:16.231+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:22:16.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:16.257+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.039 seconds
[2023-06-08T19:22:46.606+0000] {processor.py:153} INFO - Started process (PID=19400) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:46.607+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:22:46.607+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:22:46.607+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:46.623+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:22:46.621+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:22:46.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:22:46.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.040 seconds
[2023-06-08T19:23:17.118+0000] {processor.py:153} INFO - Started process (PID=19454) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:17.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:23:17.121+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:23:17.121+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:17.148+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:23:17.145+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:23:17.149+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:17.175+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.060 seconds
[2023-06-08T19:23:47.334+0000] {processor.py:153} INFO - Started process (PID=19508) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:47.335+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:23:47.335+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:23:47.335+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:47.349+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:23:47.346+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:23:47.350+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:23:47.368+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.037 seconds
[2023-06-08T19:24:17.996+0000] {processor.py:153} INFO - Started process (PID=19562) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:17.997+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:24:17.998+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:24:17.998+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:18.010+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:24:18.008+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:24:18.011+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:18.030+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.037 seconds
[2023-06-08T19:24:48.342+0000] {processor.py:153} INFO - Started process (PID=19616) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:48.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:24:48.344+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:24:48.343+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:48.357+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:24:48.355+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:24:48.358+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:24:48.380+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.041 seconds
[2023-06-08T19:25:18.753+0000] {processor.py:153} INFO - Started process (PID=19670) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:18.754+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:25:18.755+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:25:18.754+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:18.766+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:25:18.764+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:25:18.767+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:18.785+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.036 seconds
[2023-06-08T19:25:49.109+0000] {processor.py:153} INFO - Started process (PID=19724) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:49.111+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:25:49.112+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:25:49.112+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:49.128+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:25:49.125+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:25:49.130+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:25:49.149+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.043 seconds
[2023-06-08T19:26:19.463+0000] {processor.py:153} INFO - Started process (PID=19778) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:19.464+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:26:19.464+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:26:19.464+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:19.478+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:26:19.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:26:19.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:19.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.041 seconds
[2023-06-08T19:26:50.063+0000] {processor.py:153} INFO - Started process (PID=19832) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:50.064+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:26:50.065+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:26:50.065+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:50.080+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:26:50.077+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:26:50.082+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:26:50.107+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.049 seconds
[2023-06-08T19:27:20.698+0000] {processor.py:153} INFO - Started process (PID=19886) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:20.699+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:27:20.700+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:27:20.700+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:20.720+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:27:20.715+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:27:20.721+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:20.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.047 seconds
[2023-06-08T19:27:50.966+0000] {processor.py:153} INFO - Started process (PID=19940) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:50.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:27:50.968+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:27:50.968+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:51.002+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:27:50.994+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:27:51.004+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:27:51.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.074 seconds
[2023-06-08T19:28:21.643+0000] {processor.py:153} INFO - Started process (PID=19993) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:21.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:28:21.645+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:28:21.645+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:21.658+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:28:21.656+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:28:21.659+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:21.678+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.038 seconds
[2023-06-08T19:28:52.146+0000] {processor.py:153} INFO - Started process (PID=20048) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:52.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:28:52.149+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:28:52.149+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:52.164+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:28:52.161+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:28:52.165+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:28:52.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.047 seconds
[2023-06-08T19:29:22.428+0000] {processor.py:153} INFO - Started process (PID=20102) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:22.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:29:22.431+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:29:22.430+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:22.452+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:29:22.448+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:29:22.456+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:22.482+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.058 seconds
[2023-06-08T19:29:52.886+0000] {processor.py:153} INFO - Started process (PID=20157) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:52.887+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:29:52.888+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:29:52.888+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:52.903+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:29:52.900+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:29:52.905+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:29:52.925+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.043 seconds
[2023-06-08T19:30:23.115+0000] {processor.py:153} INFO - Started process (PID=20211) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:23.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:30:23.117+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:30:23.117+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:23.132+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:30:23.129+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:30:23.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:23.157+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.046 seconds
[2023-06-08T19:30:53.436+0000] {processor.py:153} INFO - Started process (PID=20266) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:53.437+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:30:53.438+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:30:53.438+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:53.455+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:30:53.451+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:30:53.456+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:30:53.479+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.046 seconds
[2023-06-08T19:31:23.706+0000] {processor.py:153} INFO - Started process (PID=20320) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:23.707+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:31:23.707+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:31:23.707+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:23.721+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:31:23.719+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:31:23.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:23.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.042 seconds
[2023-06-08T19:31:54.092+0000] {processor.py:153} INFO - Started process (PID=20374) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:54.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:31:54.094+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:31:54.094+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:54.110+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:31:54.107+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:31:54.111+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:31:54.132+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.044 seconds
[2023-06-08T19:32:24.306+0000] {processor.py:153} INFO - Started process (PID=20428) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:24.307+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:32:24.308+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:32:24.308+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:24.319+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:32:24.317+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:32:24.320+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:24.343+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.040 seconds
[2023-06-08T19:32:54.567+0000] {processor.py:153} INFO - Started process (PID=20482) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:54.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:32:54.568+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:32:54.568+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:54.583+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:32:54.580+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:32:54.584+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:32:54.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.044 seconds
[2023-06-08T19:33:24.931+0000] {processor.py:153} INFO - Started process (PID=20536) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:24.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:33:24.932+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:33:24.932+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:24.947+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:33:24.945+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:33:24.948+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:24.969+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.042 seconds
[2023-06-08T19:33:55.219+0000] {processor.py:153} INFO - Started process (PID=20590) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:55.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:33:55.221+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:33:55.221+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:55.233+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:33:55.231+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:33:55.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:33:55.253+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.038 seconds
[2023-06-08T19:34:25.434+0000] {processor.py:153} INFO - Started process (PID=20645) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:25.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:34:25.435+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:25.435+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:25.449+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:25.446+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:34:25.449+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:25.469+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.040 seconds
[2023-06-08T19:34:33.639+0000] {processor.py:153} INFO - Started process (PID=20664) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:33.640+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:34:33.641+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:33.641+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:33.661+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:33.659+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:34:33.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:33.681+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.045 seconds
[2023-06-08T19:34:39.926+0000] {processor.py:153} INFO - Started process (PID=20676) to work on /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:39.927+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl_pipeline_employes.py for tasks to queue
[2023-06-08T19:34:39.928+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:39.928+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:39.951+0000] {logging_mixin.py:137} INFO - [2023-06-08T19:34:39.948+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/etl_pipeline_employes.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_pipeline_employes.py", line 4, in <module>
    from airflow.operators.eamil_operator import EmailOperator
ModuleNotFoundError: No module named 'airflow.operators.eamil_operator'
[2023-06-08T19:34:39.952+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_pipeline_employes.py
[2023-06-08T19:34:39.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl_pipeline_employes.py took 0.049 seconds
